// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventMessage.proto

package com.gasmonitor.collector;

public final class EventProbuf {
  private EventProbuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface EventMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EventMessage)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required string hardwareId = 1;</code>
     */
    boolean hasHardwareId();
    /**
     * <code>required string hardwareId = 1;</code>
     */
    String getHardwareId();
    /**
     * <code>required string hardwareId = 1;</code>
     */
    com.google.protobuf.ByteString
        getHardwareIdBytes();

    /**
     * <code>optional double temperature = 2;</code>
     */
    boolean hasTemperature();
    /**
     * <code>optional double temperature = 2;</code>
     */
    double getTemperature();

    /**
     * <code>optional double pressure = 3;</code>
     */
    boolean hasPressure();
    /**
     * <code>optional double pressure = 3;</code>
     */
    double getPressure();

    /**
     * <code>optional double standard = 4;</code>
     */
    boolean hasStandard();
    /**
     * <code>optional double standard = 4;</code>
     */
    double getStandard();

    /**
     * <code>optional double running = 5;</code>
     */
    boolean hasRunning();
    /**
     * <code>optional double running = 5;</code>
     */
    double getRunning();

    /**
     * <code>optional double summary = 6;</code>
     */
    boolean hasSummary();
    /**
     * <code>optional double summary = 6;</code>
     */
    double getSummary();

    /**
     * <code>optional double surplus = 7;</code>
     */
    boolean hasSurplus();
    /**
     * <code>optional double surplus = 7;</code>
     */
    double getSurplus();

    /**
     * <code>optional double analog1 = 8;</code>
     */
    boolean hasAnalog1();
    /**
     * <code>optional double analog1 = 8;</code>
     */
    double getAnalog1();

    /**
     * <code>optional double analog2 = 9;</code>
     */
    boolean hasAnalog2();
    /**
     * <code>optional double analog2 = 9;</code>
     */
    double getAnalog2();

    /**
     * <code>optional double analog3 = 10;</code>
     */
    boolean hasAnalog3();
    /**
     * <code>optional double analog3 = 10;</code>
     */
    double getAnalog3();

    /**
     * <code>optional double analog4 = 11;</code>
     */
    boolean hasAnalog4();
    /**
     * <code>optional double analog4 = 11;</code>
     */
    double getAnalog4();

    /**
     * <code>optional int32 switch1 = 12;</code>
     */
    boolean hasSwitch1();
    /**
     * <code>optional int32 switch1 = 12;</code>
     */
    int getSwitch1();

    /**
     * <code>optional int32 switch2 = 13;</code>
     */
    boolean hasSwitch2();
    /**
     * <code>optional int32 switch2 = 13;</code>
     */
    int getSwitch2();

    /**
     * <code>optional int32 switch3 = 14;</code>
     */
    boolean hasSwitch3();
    /**
     * <code>optional int32 switch3 = 14;</code>
     */
    int getSwitch3();

    /**
     * <code>optional int32 switch4 = 15;</code>
     */
    boolean hasSwitch4();
    /**
     * <code>optional int32 switch4 = 15;</code>
     */
    int getSwitch4();

    /**
     * <code>optional int32 ac220 = 16;</code>
     */
    boolean hasAc220();
    /**
     * <code>optional int32 ac220 = 16;</code>
     */
    int getAc220();

    /**
     * <code>optional int32 battery = 17;</code>
     */
    boolean hasBattery();
    /**
     * <code>optional int32 battery = 17;</code>
     */
    int getBattery();

    /**
     * <code>optional int32 solar = 18;</code>
     */
    boolean hasSolar();
    /**
     * <code>optional int32 solar = 18;</code>
     */
    int getSolar();

    /**
     * <code>optional uint64 pointtime = 19;</code>
     */
    boolean hasPointtime();
    /**
     * <code>optional uint64 pointtime = 19;</code>
     */
    long getPointtime();
  }
  /**
   * Protobuf type {@code EventMessage}
   */
  public static final class EventMessage extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:EventMessage)
      EventMessageOrBuilder {
    // Use EventMessage.newBuilder() to construct.
    private EventMessage(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EventMessage(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final EventMessage defaultInstance;
    public static EventMessage getDefaultInstance() {
      return defaultInstance;
    }

    public EventMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private EventMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              hardwareId_ = bs;
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              temperature_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              pressure_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              standard_ = input.readDouble();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              running_ = input.readDouble();
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              summary_ = input.readDouble();
              break;
            }
            case 57: {
              bitField0_ |= 0x00000040;
              surplus_ = input.readDouble();
              break;
            }
            case 65: {
              bitField0_ |= 0x00000080;
              analog1_ = input.readDouble();
              break;
            }
            case 73: {
              bitField0_ |= 0x00000100;
              analog2_ = input.readDouble();
              break;
            }
            case 81: {
              bitField0_ |= 0x00000200;
              analog3_ = input.readDouble();
              break;
            }
            case 89: {
              bitField0_ |= 0x00000400;
              analog4_ = input.readDouble();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              switch1_ = input.readInt32();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              switch2_ = input.readInt32();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              switch3_ = input.readInt32();
              break;
            }
            case 120: {
              bitField0_ |= 0x00004000;
              switch4_ = input.readInt32();
              break;
            }
            case 128: {
              bitField0_ |= 0x00008000;
              ac220_ = input.readInt32();
              break;
            }
            case 136: {
              bitField0_ |= 0x00010000;
              battery_ = input.readInt32();
              break;
            }
            case 144: {
              bitField0_ |= 0x00020000;
              solar_ = input.readInt32();
              break;
            }
            case 152: {
              bitField0_ |= 0x00040000;
              pointtime_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<EventMessage> PARSER =
        new com.google.protobuf.AbstractParser<EventMessage>() {
      public EventMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EventMessage(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<EventMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int HARDWAREID_FIELD_NUMBER = 1;
    private Object hardwareId_;
    /**
     * <code>required string hardwareId = 1;</code>
     */
    public boolean hasHardwareId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string hardwareId = 1;</code>
     */
    public String getHardwareId() {
      Object ref = hardwareId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          hardwareId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string hardwareId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHardwareIdBytes() {
      Object ref = hardwareId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        hardwareId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEMPERATURE_FIELD_NUMBER = 2;
    private double temperature_;
    /**
     * <code>optional double temperature = 2;</code>
     */
    public boolean hasTemperature() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional double temperature = 2;</code>
     */
    public double getTemperature() {
      return temperature_;
    }

    public static final int PRESSURE_FIELD_NUMBER = 3;
    private double pressure_;
    /**
     * <code>optional double pressure = 3;</code>
     */
    public boolean hasPressure() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional double pressure = 3;</code>
     */
    public double getPressure() {
      return pressure_;
    }

    public static final int STANDARD_FIELD_NUMBER = 4;
    private double standard_;
    /**
     * <code>optional double standard = 4;</code>
     */
    public boolean hasStandard() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional double standard = 4;</code>
     */
    public double getStandard() {
      return standard_;
    }

    public static final int RUNNING_FIELD_NUMBER = 5;
    private double running_;
    /**
     * <code>optional double running = 5;</code>
     */
    public boolean hasRunning() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional double running = 5;</code>
     */
    public double getRunning() {
      return running_;
    }

    public static final int SUMMARY_FIELD_NUMBER = 6;
    private double summary_;
    /**
     * <code>optional double summary = 6;</code>
     */
    public boolean hasSummary() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional double summary = 6;</code>
     */
    public double getSummary() {
      return summary_;
    }

    public static final int SURPLUS_FIELD_NUMBER = 7;
    private double surplus_;
    /**
     * <code>optional double surplus = 7;</code>
     */
    public boolean hasSurplus() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional double surplus = 7;</code>
     */
    public double getSurplus() {
      return surplus_;
    }

    public static final int ANALOG1_FIELD_NUMBER = 8;
    private double analog1_;
    /**
     * <code>optional double analog1 = 8;</code>
     */
    public boolean hasAnalog1() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional double analog1 = 8;</code>
     */
    public double getAnalog1() {
      return analog1_;
    }

    public static final int ANALOG2_FIELD_NUMBER = 9;
    private double analog2_;
    /**
     * <code>optional double analog2 = 9;</code>
     */
    public boolean hasAnalog2() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional double analog2 = 9;</code>
     */
    public double getAnalog2() {
      return analog2_;
    }

    public static final int ANALOG3_FIELD_NUMBER = 10;
    private double analog3_;
    /**
     * <code>optional double analog3 = 10;</code>
     */
    public boolean hasAnalog3() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional double analog3 = 10;</code>
     */
    public double getAnalog3() {
      return analog3_;
    }

    public static final int ANALOG4_FIELD_NUMBER = 11;
    private double analog4_;
    /**
     * <code>optional double analog4 = 11;</code>
     */
    public boolean hasAnalog4() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional double analog4 = 11;</code>
     */
    public double getAnalog4() {
      return analog4_;
    }

    public static final int SWITCH1_FIELD_NUMBER = 12;
    private int switch1_;
    /**
     * <code>optional int32 switch1 = 12;</code>
     */
    public boolean hasSwitch1() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional int32 switch1 = 12;</code>
     */
    public int getSwitch1() {
      return switch1_;
    }

    public static final int SWITCH2_FIELD_NUMBER = 13;
    private int switch2_;
    /**
     * <code>optional int32 switch2 = 13;</code>
     */
    public boolean hasSwitch2() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional int32 switch2 = 13;</code>
     */
    public int getSwitch2() {
      return switch2_;
    }

    public static final int SWITCH3_FIELD_NUMBER = 14;
    private int switch3_;
    /**
     * <code>optional int32 switch3 = 14;</code>
     */
    public boolean hasSwitch3() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional int32 switch3 = 14;</code>
     */
    public int getSwitch3() {
      return switch3_;
    }

    public static final int SWITCH4_FIELD_NUMBER = 15;
    private int switch4_;
    /**
     * <code>optional int32 switch4 = 15;</code>
     */
    public boolean hasSwitch4() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional int32 switch4 = 15;</code>
     */
    public int getSwitch4() {
      return switch4_;
    }

    public static final int AC220_FIELD_NUMBER = 16;
    private int ac220_;
    /**
     * <code>optional int32 ac220 = 16;</code>
     */
    public boolean hasAc220() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>optional int32 ac220 = 16;</code>
     */
    public int getAc220() {
      return ac220_;
    }

    public static final int BATTERY_FIELD_NUMBER = 17;
    private int battery_;
    /**
     * <code>optional int32 battery = 17;</code>
     */
    public boolean hasBattery() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    /**
     * <code>optional int32 battery = 17;</code>
     */
    public int getBattery() {
      return battery_;
    }

    public static final int SOLAR_FIELD_NUMBER = 18;
    private int solar_;
    /**
     * <code>optional int32 solar = 18;</code>
     */
    public boolean hasSolar() {
      return ((bitField0_ & 0x00020000) == 0x00020000);
    }
    /**
     * <code>optional int32 solar = 18;</code>
     */
    public int getSolar() {
      return solar_;
    }

    public static final int POINTTIME_FIELD_NUMBER = 19;
    private long pointtime_;
    /**
     * <code>optional uint64 pointtime = 19;</code>
     */
    public boolean hasPointtime() {
      return ((bitField0_ & 0x00040000) == 0x00040000);
    }
    /**
     * <code>optional uint64 pointtime = 19;</code>
     */
    public long getPointtime() {
      return pointtime_;
    }

    private void initFields() {
      hardwareId_ = "";
      temperature_ = 0D;
      pressure_ = 0D;
      standard_ = 0D;
      running_ = 0D;
      summary_ = 0D;
      surplus_ = 0D;
      analog1_ = 0D;
      analog2_ = 0D;
      analog3_ = 0D;
      analog4_ = 0D;
      switch1_ = 0;
      switch2_ = 0;
      switch3_ = 0;
      switch4_ = 0;
      ac220_ = 0;
      battery_ = 0;
      solar_ = 0;
      pointtime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHardwareId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getHardwareIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, temperature_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, pressure_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, standard_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, running_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(6, summary_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeDouble(7, surplus_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeDouble(8, analog1_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeDouble(9, analog2_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeDouble(10, analog3_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeDouble(11, analog4_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(12, switch1_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(13, switch2_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt32(14, switch3_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeInt32(15, switch4_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeInt32(16, ac220_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeInt32(17, battery_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        output.writeInt32(18, solar_);
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        output.writeUInt64(19, pointtime_);
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getHardwareIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, temperature_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, pressure_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, standard_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, running_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, summary_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, surplus_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, analog1_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(9, analog2_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(10, analog3_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(11, analog4_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, switch1_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, switch2_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, switch3_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, switch4_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(16, ac220_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(17, battery_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(18, solar_);
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(19, pointtime_);
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static EventMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EventMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EventMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EventMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EventMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static EventMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static EventMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static EventMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static EventMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static EventMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(EventMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code EventMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          EventMessage, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:EventMessage)
        EventMessageOrBuilder {
      // Construct using com.gasmonitor.collector.EventProbuf.EventMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        hardwareId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        temperature_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        pressure_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        standard_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        running_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        summary_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        surplus_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        analog1_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000080);
        analog2_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000100);
        analog3_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000200);
        analog4_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000400);
        switch1_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        switch2_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        switch3_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        switch4_ = 0;
        bitField0_ = (bitField0_ & ~0x00004000);
        ac220_ = 0;
        bitField0_ = (bitField0_ & ~0x00008000);
        battery_ = 0;
        bitField0_ = (bitField0_ & ~0x00010000);
        solar_ = 0;
        bitField0_ = (bitField0_ & ~0x00020000);
        pointtime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00040000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public EventMessage getDefaultInstanceForType() {
        return EventMessage.getDefaultInstance();
      }

      public EventMessage build() {
        EventMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public EventMessage buildPartial() {
        EventMessage result = new EventMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.hardwareId_ = hardwareId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.temperature_ = temperature_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.pressure_ = pressure_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.standard_ = standard_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.running_ = running_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.summary_ = summary_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.surplus_ = surplus_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.analog1_ = analog1_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.analog2_ = analog2_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.analog3_ = analog3_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.analog4_ = analog4_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.switch1_ = switch1_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.switch2_ = switch2_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.switch3_ = switch3_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.switch4_ = switch4_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.ac220_ = ac220_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.battery_ = battery_;
        if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
          to_bitField0_ |= 0x00020000;
        }
        result.solar_ = solar_;
        if (((from_bitField0_ & 0x00040000) == 0x00040000)) {
          to_bitField0_ |= 0x00040000;
        }
        result.pointtime_ = pointtime_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(EventMessage other) {
        if (other == EventMessage.getDefaultInstance()) return this;
        if (other.hasHardwareId()) {
          bitField0_ |= 0x00000001;
          hardwareId_ = other.hardwareId_;
          
        }
        if (other.hasTemperature()) {
          setTemperature(other.getTemperature());
        }
        if (other.hasPressure()) {
          setPressure(other.getPressure());
        }
        if (other.hasStandard()) {
          setStandard(other.getStandard());
        }
        if (other.hasRunning()) {
          setRunning(other.getRunning());
        }
        if (other.hasSummary()) {
          setSummary(other.getSummary());
        }
        if (other.hasSurplus()) {
          setSurplus(other.getSurplus());
        }
        if (other.hasAnalog1()) {
          setAnalog1(other.getAnalog1());
        }
        if (other.hasAnalog2()) {
          setAnalog2(other.getAnalog2());
        }
        if (other.hasAnalog3()) {
          setAnalog3(other.getAnalog3());
        }
        if (other.hasAnalog4()) {
          setAnalog4(other.getAnalog4());
        }
        if (other.hasSwitch1()) {
          setSwitch1(other.getSwitch1());
        }
        if (other.hasSwitch2()) {
          setSwitch2(other.getSwitch2());
        }
        if (other.hasSwitch3()) {
          setSwitch3(other.getSwitch3());
        }
        if (other.hasSwitch4()) {
          setSwitch4(other.getSwitch4());
        }
        if (other.hasAc220()) {
          setAc220(other.getAc220());
        }
        if (other.hasBattery()) {
          setBattery(other.getBattery());
        }
        if (other.hasSolar()) {
          setSolar(other.getSolar());
        }
        if (other.hasPointtime()) {
          setPointtime(other.getPointtime());
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHardwareId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EventMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EventMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object hardwareId_ = "";
      /**
       * <code>required string hardwareId = 1;</code>
       */
      public boolean hasHardwareId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string hardwareId = 1;</code>
       */
      public String getHardwareId() {
        Object ref = hardwareId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            hardwareId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string hardwareId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHardwareIdBytes() {
        Object ref = hardwareId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          hardwareId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string hardwareId = 1;</code>
       */
      public Builder setHardwareId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        hardwareId_ = value;
        
        return this;
      }
      /**
       * <code>required string hardwareId = 1;</code>
       */
      public Builder clearHardwareId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        hardwareId_ = getDefaultInstance().getHardwareId();
        
        return this;
      }
      /**
       * <code>required string hardwareId = 1;</code>
       */
      public Builder setHardwareIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        hardwareId_ = value;
        
        return this;
      }

      private double temperature_ ;
      /**
       * <code>optional double temperature = 2;</code>
       */
      public boolean hasTemperature() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional double temperature = 2;</code>
       */
      public double getTemperature() {
        return temperature_;
      }
      /**
       * <code>optional double temperature = 2;</code>
       */
      public Builder setTemperature(double value) {
        bitField0_ |= 0x00000002;
        temperature_ = value;
        
        return this;
      }
      /**
       * <code>optional double temperature = 2;</code>
       */
      public Builder clearTemperature() {
        bitField0_ = (bitField0_ & ~0x00000002);
        temperature_ = 0D;
        
        return this;
      }

      private double pressure_ ;
      /**
       * <code>optional double pressure = 3;</code>
       */
      public boolean hasPressure() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double pressure = 3;</code>
       */
      public double getPressure() {
        return pressure_;
      }
      /**
       * <code>optional double pressure = 3;</code>
       */
      public Builder setPressure(double value) {
        bitField0_ |= 0x00000004;
        pressure_ = value;
        
        return this;
      }
      /**
       * <code>optional double pressure = 3;</code>
       */
      public Builder clearPressure() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pressure_ = 0D;
        
        return this;
      }

      private double standard_ ;
      /**
       * <code>optional double standard = 4;</code>
       */
      public boolean hasStandard() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double standard = 4;</code>
       */
      public double getStandard() {
        return standard_;
      }
      /**
       * <code>optional double standard = 4;</code>
       */
      public Builder setStandard(double value) {
        bitField0_ |= 0x00000008;
        standard_ = value;
        
        return this;
      }
      /**
       * <code>optional double standard = 4;</code>
       */
      public Builder clearStandard() {
        bitField0_ = (bitField0_ & ~0x00000008);
        standard_ = 0D;
        
        return this;
      }

      private double running_ ;
      /**
       * <code>optional double running = 5;</code>
       */
      public boolean hasRunning() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional double running = 5;</code>
       */
      public double getRunning() {
        return running_;
      }
      /**
       * <code>optional double running = 5;</code>
       */
      public Builder setRunning(double value) {
        bitField0_ |= 0x00000010;
        running_ = value;
        
        return this;
      }
      /**
       * <code>optional double running = 5;</code>
       */
      public Builder clearRunning() {
        bitField0_ = (bitField0_ & ~0x00000010);
        running_ = 0D;
        
        return this;
      }

      private double summary_ ;
      /**
       * <code>optional double summary = 6;</code>
       */
      public boolean hasSummary() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional double summary = 6;</code>
       */
      public double getSummary() {
        return summary_;
      }
      /**
       * <code>optional double summary = 6;</code>
       */
      public Builder setSummary(double value) {
        bitField0_ |= 0x00000020;
        summary_ = value;
        
        return this;
      }
      /**
       * <code>optional double summary = 6;</code>
       */
      public Builder clearSummary() {
        bitField0_ = (bitField0_ & ~0x00000020);
        summary_ = 0D;
        
        return this;
      }

      private double surplus_ ;
      /**
       * <code>optional double surplus = 7;</code>
       */
      public boolean hasSurplus() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional double surplus = 7;</code>
       */
      public double getSurplus() {
        return surplus_;
      }
      /**
       * <code>optional double surplus = 7;</code>
       */
      public Builder setSurplus(double value) {
        bitField0_ |= 0x00000040;
        surplus_ = value;
        
        return this;
      }
      /**
       * <code>optional double surplus = 7;</code>
       */
      public Builder clearSurplus() {
        bitField0_ = (bitField0_ & ~0x00000040);
        surplus_ = 0D;
        
        return this;
      }

      private double analog1_ ;
      /**
       * <code>optional double analog1 = 8;</code>
       */
      public boolean hasAnalog1() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional double analog1 = 8;</code>
       */
      public double getAnalog1() {
        return analog1_;
      }
      /**
       * <code>optional double analog1 = 8;</code>
       */
      public Builder setAnalog1(double value) {
        bitField0_ |= 0x00000080;
        analog1_ = value;
        
        return this;
      }
      /**
       * <code>optional double analog1 = 8;</code>
       */
      public Builder clearAnalog1() {
        bitField0_ = (bitField0_ & ~0x00000080);
        analog1_ = 0D;
        
        return this;
      }

      private double analog2_ ;
      /**
       * <code>optional double analog2 = 9;</code>
       */
      public boolean hasAnalog2() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional double analog2 = 9;</code>
       */
      public double getAnalog2() {
        return analog2_;
      }
      /**
       * <code>optional double analog2 = 9;</code>
       */
      public Builder setAnalog2(double value) {
        bitField0_ |= 0x00000100;
        analog2_ = value;
        
        return this;
      }
      /**
       * <code>optional double analog2 = 9;</code>
       */
      public Builder clearAnalog2() {
        bitField0_ = (bitField0_ & ~0x00000100);
        analog2_ = 0D;
        
        return this;
      }

      private double analog3_ ;
      /**
       * <code>optional double analog3 = 10;</code>
       */
      public boolean hasAnalog3() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional double analog3 = 10;</code>
       */
      public double getAnalog3() {
        return analog3_;
      }
      /**
       * <code>optional double analog3 = 10;</code>
       */
      public Builder setAnalog3(double value) {
        bitField0_ |= 0x00000200;
        analog3_ = value;
        
        return this;
      }
      /**
       * <code>optional double analog3 = 10;</code>
       */
      public Builder clearAnalog3() {
        bitField0_ = (bitField0_ & ~0x00000200);
        analog3_ = 0D;
        
        return this;
      }

      private double analog4_ ;
      /**
       * <code>optional double analog4 = 11;</code>
       */
      public boolean hasAnalog4() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional double analog4 = 11;</code>
       */
      public double getAnalog4() {
        return analog4_;
      }
      /**
       * <code>optional double analog4 = 11;</code>
       */
      public Builder setAnalog4(double value) {
        bitField0_ |= 0x00000400;
        analog4_ = value;
        
        return this;
      }
      /**
       * <code>optional double analog4 = 11;</code>
       */
      public Builder clearAnalog4() {
        bitField0_ = (bitField0_ & ~0x00000400);
        analog4_ = 0D;
        
        return this;
      }

      private int switch1_ ;
      /**
       * <code>optional int32 switch1 = 12;</code>
       */
      public boolean hasSwitch1() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional int32 switch1 = 12;</code>
       */
      public int getSwitch1() {
        return switch1_;
      }
      /**
       * <code>optional int32 switch1 = 12;</code>
       */
      public Builder setSwitch1(int value) {
        bitField0_ |= 0x00000800;
        switch1_ = value;
        
        return this;
      }
      /**
       * <code>optional int32 switch1 = 12;</code>
       */
      public Builder clearSwitch1() {
        bitField0_ = (bitField0_ & ~0x00000800);
        switch1_ = 0;
        
        return this;
      }

      private int switch2_ ;
      /**
       * <code>optional int32 switch2 = 13;</code>
       */
      public boolean hasSwitch2() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional int32 switch2 = 13;</code>
       */
      public int getSwitch2() {
        return switch2_;
      }
      /**
       * <code>optional int32 switch2 = 13;</code>
       */
      public Builder setSwitch2(int value) {
        bitField0_ |= 0x00001000;
        switch2_ = value;
        
        return this;
      }
      /**
       * <code>optional int32 switch2 = 13;</code>
       */
      public Builder clearSwitch2() {
        bitField0_ = (bitField0_ & ~0x00001000);
        switch2_ = 0;
        
        return this;
      }

      private int switch3_ ;
      /**
       * <code>optional int32 switch3 = 14;</code>
       */
      public boolean hasSwitch3() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional int32 switch3 = 14;</code>
       */
      public int getSwitch3() {
        return switch3_;
      }
      /**
       * <code>optional int32 switch3 = 14;</code>
       */
      public Builder setSwitch3(int value) {
        bitField0_ |= 0x00002000;
        switch3_ = value;
        
        return this;
      }
      /**
       * <code>optional int32 switch3 = 14;</code>
       */
      public Builder clearSwitch3() {
        bitField0_ = (bitField0_ & ~0x00002000);
        switch3_ = 0;
        
        return this;
      }

      private int switch4_ ;
      /**
       * <code>optional int32 switch4 = 15;</code>
       */
      public boolean hasSwitch4() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional int32 switch4 = 15;</code>
       */
      public int getSwitch4() {
        return switch4_;
      }
      /**
       * <code>optional int32 switch4 = 15;</code>
       */
      public Builder setSwitch4(int value) {
        bitField0_ |= 0x00004000;
        switch4_ = value;
        
        return this;
      }
      /**
       * <code>optional int32 switch4 = 15;</code>
       */
      public Builder clearSwitch4() {
        bitField0_ = (bitField0_ & ~0x00004000);
        switch4_ = 0;
        
        return this;
      }

      private int ac220_ ;
      /**
       * <code>optional int32 ac220 = 16;</code>
       */
      public boolean hasAc220() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>optional int32 ac220 = 16;</code>
       */
      public int getAc220() {
        return ac220_;
      }
      /**
       * <code>optional int32 ac220 = 16;</code>
       */
      public Builder setAc220(int value) {
        bitField0_ |= 0x00008000;
        ac220_ = value;
        
        return this;
      }
      /**
       * <code>optional int32 ac220 = 16;</code>
       */
      public Builder clearAc220() {
        bitField0_ = (bitField0_ & ~0x00008000);
        ac220_ = 0;
        
        return this;
      }

      private int battery_ ;
      /**
       * <code>optional int32 battery = 17;</code>
       */
      public boolean hasBattery() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      /**
       * <code>optional int32 battery = 17;</code>
       */
      public int getBattery() {
        return battery_;
      }
      /**
       * <code>optional int32 battery = 17;</code>
       */
      public Builder setBattery(int value) {
        bitField0_ |= 0x00010000;
        battery_ = value;
        
        return this;
      }
      /**
       * <code>optional int32 battery = 17;</code>
       */
      public Builder clearBattery() {
        bitField0_ = (bitField0_ & ~0x00010000);
        battery_ = 0;
        
        return this;
      }

      private int solar_ ;
      /**
       * <code>optional int32 solar = 18;</code>
       */
      public boolean hasSolar() {
        return ((bitField0_ & 0x00020000) == 0x00020000);
      }
      /**
       * <code>optional int32 solar = 18;</code>
       */
      public int getSolar() {
        return solar_;
      }
      /**
       * <code>optional int32 solar = 18;</code>
       */
      public Builder setSolar(int value) {
        bitField0_ |= 0x00020000;
        solar_ = value;
        
        return this;
      }
      /**
       * <code>optional int32 solar = 18;</code>
       */
      public Builder clearSolar() {
        bitField0_ = (bitField0_ & ~0x00020000);
        solar_ = 0;
        
        return this;
      }

      private long pointtime_ ;
      /**
       * <code>optional uint64 pointtime = 19;</code>
       */
      public boolean hasPointtime() {
        return ((bitField0_ & 0x00040000) == 0x00040000);
      }
      /**
       * <code>optional uint64 pointtime = 19;</code>
       */
      public long getPointtime() {
        return pointtime_;
      }
      /**
       * <code>optional uint64 pointtime = 19;</code>
       */
      public Builder setPointtime(long value) {
        bitField0_ |= 0x00040000;
        pointtime_ = value;
        
        return this;
      }
      /**
       * <code>optional uint64 pointtime = 19;</code>
       */
      public Builder clearPointtime() {
        bitField0_ = (bitField0_ & ~0x00040000);
        pointtime_ = 0L;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:EventMessage)
    }

    static {
      defaultInstance = new EventMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:EventMessage)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
